### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
@bryanbraun:

1. register for GitHub Actions https://github.com/features/actions
2. we can't use the alias `node` yet, so I went with the latest 12 LTS
3. before you merge this make sure you remove any Travis CI hooks/apps/integrations

Preview: <https://github.com/XhmikosR/anchorjs/runs/281158300>

This will fire after the above and after you merge this for security reasons.

### CODE REVIEW

**Comment by bryanbraun** [comment]
Ooh, interesting. I haven't tried Github actions before. It would be nice to consolidate on Github...

I'd feel a bit more comfortable about taking the leap [after Github Actions comes out of beta on November 15th](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/#sign-up-for-the-beta). Maybe we can hold on merging this PR until then?

**Comment by XhmikosR** [comment]
@bryanbraun just register for it regardless and you decide later :P

That being said, I have already switched to GH Actions on almost all my projects. This project is pretty simple, so you should be fine :)

**Comment by XhmikosR** [comment]
Including bootstrap, bootstrapcdn etc.

**Comment by XhmikosR** [comment]
@bryanbraun note that you will see this firing after you merge. After you merge and if you are happy with the result, see my third point in my OP.

**Pull request merged**
