### PR TITLE
fix issue Add the scroll-margin-top technique to the docs

### PR DESCRIPTION
**Pull request by tusharck**

### CODE REVIEW

**Review by bryanbraun — CHANGES_REQUESTED** [review]
Hey @tusharck, thanks for giving this one a shot.

You combined the new sticky header technique with the existing technique, which isn't really what I was expecting. That's probably my fault for not being very clear on the issue.

The thing I had in mind was to document both the old and new techniques. For example, after the code example for the existing technique, you could say something like this:

> Alternatively, you could use the newer `scroll-margin-top` property:
>
> :target {
>     scroll-margin-top: 80px;
> }
>
> *Note: This may not be supported in all browsers... please [check caniuse for details](https://caniuse.com/?search=scroll-margin-top).*

Does that make sense? Could you update the PR with that in mind?

**Comment by tusharck** [comment]
Hey @bryanbraun , point noted, i will make the changes and update you once done.

**Comment by tusharck** [comment]
I made the changes as requested please review.

**Review by bryanbraun — APPROVED** [review]
@tusharck, this is close enough to move forward. I'll go ahead and merge and I can make some tweaks in a follow-up commit if needed. Thanks for contributing. :)

**Pull request merged**
