### PR TITLE
Trim of trailing and multiple hyphens (renew)

### PR DESCRIPTION
**Pull request by iKwinto**
Making of more beautiful IDs.

Example:
```
<h1>Заголовок, содержащий 29 не-ASCII символов</h1>
```
generates originally:
```
#-29--ascii-
```
with my patch:
```
#29-ascii
```

### CODE REVIEW

**Comment by iKwinto** [comment]
@XhmikosR Please could you reply?

**Comment by XhmikosR** [comment]
It's not my project :p

**Comment by bryanbraun** [comment]
@iKwinto, at first glance this looks really good! Thanks for the contribution :+1: 

I think I may fiddle with the regex a bit to see if I can combine it with expression [on line 47](https://github.com/iKwinto/anchorjs/commit/23cad299038e3f4afb3a3e2c83ef1b22a96a3e99#diff-2257e354fffd4c7d0ba9d616daed74eaR47), without making it too unreadable.

Unless anything comes up, I'm planning on merging it this week.

**Comment by bryanbraun** [comment]
This was merged. Thanks again!

**Pull request closed without merging**
