### PR TITLE
Trim of trailing and multiple hyphens

### PR DESCRIPTION
**Pull request by iKwinto**
Making of more beautiful IDs. See example in code.

### CODE REVIEW

**Comment by vaughany** [comment]
:+1:

**Comment by iKwinto** [comment]
@vaughany 
Tried myself `<h2>Title <small>some text</small></h2>` and I have this result:
```
#title-some-text
```

**Comment by vaughany** [comment]
Sorry@iKwinto, I meant to say that as AnchorJS currently stands, trailing slashes are not stripped and that your code would be a valuable addition. I didn't mean to suggest that your code doesn't work as intended (sorry!).

**Comment by iKwinto** [comment]
@vaughany All is OK. 😉

In my case it was even worse. I use some non-Latin titles and have the following results:
```
<h1>Заголовок, содержащий 29 не-ASCII символов</h1>
```
generates originally:
```
#-29--ascii-
```
with my patch:
```
#29-ascii
```

**Comment by XhmikosR** [comment]
@iKwinto: you should rebase and remove the useless patches from the branch,

**Comment by iKwinto** [comment]
@XhmikosR Unfortunately I deleted my local repository and can`t do rebase of the branch. Please reject this Pull request, and I will create a new one with pure patch.

**Comment by iKwinto** [comment]
Pure patch: https://github.com/bryanbraun/anchorjs/pull/30

**Pull request closed without merging**
