### PR TITLE
add options.base to prepend the anchor

### PR DESCRIPTION
**Pull request by gnawhleinad**
The target use-case (for me) is to support permalinks with AnchorJS. Right now, I have pages that will:

- show the anchor from the main page (e.g., `https://lilo.localhost#ohana`)
- show the anchor from the blog post (e.g., `https://lilo.localhost/stitch-rocks#ohana`)

I'd like the first line item to (also) be `https://lilo.localhost/stitch-rocks#ohana`.

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey @gnawhleinad, I'm just looking at this now. I'm wondering, is this designed as a solution for #98? If so, I'm leaning toward [this solution](https://github.com/bryanbraun/anchorjs/pull/103) since it's zero-configuration.

Or is there a different problem you are trying to solve?

**Comment by gnawhleinad** [comment]
> I'm just looking at this now. I'm wondering, is this designed as a solution for #98? If so, I'm leaning toward [this solution](https://github.com/bryanbraun/anchorjs/pull/103) since it's zero-configuration.
> 
> Or is there a different problem you are trying to solve?

@bryanbraun, I may have misinterpreted :point_up: but don't think it'd work for my use-case (as described in the OP). To share the example differently...

https://blog.github.com/ will show all posts and it's respective content which contain anchrojs' header. However, those anchors use blog.github.com and I'd like them to use the permalink'd `base`. e.g.,

| blog.github.com | blog.github.com/2018-11-20-breaks-and-holidays/ |
| --- | --- |
| screen shot 2018-11-30 at 5 44 46 pm | screen shot 2018-11-30 at 5 45 05 pm |

**Comment by bryanbraun** [comment]
Oh, I see what you mean!

In your example, if a person grabs a permalink to https://blog.github.com/#breaks-during-the-day, that link will break in the future because the the content will move off of the home page, right? So your PR provides a solution for that.

I'm on board. It seems like a common-enough use-case that it's worth addressing (I just realized I have the same situation on my personal blog).

We just have to make sure it works alongside the changes I just merged for #98. I think we could do this pretty easily by considering your option an "override". So the code might work like this (though there might be a better way to write it):

```js
// Adjust the href if there's a <base> tag. See https://github.com/bryanbraun/anchorjs/issues/98
hrefBase = document.querySelector('base') ? window.location.pathname + window.location.search : '';
hrefBase = this.options.base || hrefBase;
anchor.href = hrefBase + '#' + elementID;
```

If you want to rebase your branch trying an approach like this, I'd be down to review and merge it.

(PS: thanks for adding your own tests and docs for this PR ❤️ )

**Comment by gnawhleinad** [comment]
> In your example, if a person grabs a permalink to https://blog.github.com/#breaks-during-the-day, that link will break in the future because the the content will move off of the home page, right? So your PR provides a solution for that.

:+1:, yes!

> I'm on board. It seems like a common-enough use-case that it's worth addressing (I just realized I have the same situation on my personal blog).

:tada:, I'm glad this resolve your issue as well!

> If you want to rebase your branch trying an approach like this, I'd be down to review and merge it.

:bow:!

**Comment by bryanbraun** [comment]
Thanks! I should be able to test this out over the weekend. 👍

**Comment by bryanbraun** [comment]
This is working great. I'm merging this, and releasing a new version of AnchorJS that includes it today. 🎉

**Pull request merged**
