### PR TITLE
docs: Assorted tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
@bryanbraun please check out the individual patches and let me know.

Things left for later:

* update libs (jquery, prism)
* see if we can drop jquery; AFAICT it's only used for the show code toggle
* regenerate favicons (I will do this later myself if you can provide me with the SVG you used for the existent favicon.ico)

About the CSS prefixes, I used https://browsersl.ist/?q=defaults%2C+Explorer+%3E%3D+9

Preview: <https://suspicious-fermi-6f5f16.netlify.com/>

### CODE REVIEW

**Comment by bryanbraun** [comment]
Good call on the image compression (PNGs and SVGs).

The used-by images look so much better on retina now. Maybe I can do a similar improvement for the main logo.

The new github corner is probably a good idea to freshen it up. It looks better on retina too. :)

I like the HTTPS updates. 👍 

Also, big thanks for the netlify url! That made it easy to review. :)

_Only one question... why should we add width and height attributes to the img elements? Shouldn't we manage those things in CSS (if needed)?_

**Comment by XhmikosR** [comment]
The HTML is what is parsed first by browsers. Having the dimensions there
avoids reflows.

**Comment by XhmikosR** [comment]
Also see
https://www.afasterweb.com/2019/10/30/a-new-way-to-prevent-layout-jank-during-image-load/

**Comment by bryanbraun** [comment]
@XhmikosR Ah, yes, that makes sense! This looks great, merging now.

**Pull request merged**
