### PR TITLE
Add tooltip feature

### PR DESCRIPTION
**Pull request by catchmyfame**
Added a new option for anchor tooltips using the native html title attribute. By default no tooltips are created. You can either specify a string to be applied to all anchors created, or specify the tooltip text on a target element by setting the `data-anchorjs-tooltip` attribute. For example: `<h2 data-anchorjs-tooltip="This is a specific tooltip for this heading">Title</h2>.` Data attribute tooltips will supercede any generic tooltips (if specified).

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey, @catchmyfame I just got a chance to really look at this PR. Thanks for taking a shot at it. 😄 

I'm on board with having a new option that is turned off by default (like you show here). I'd probably want to call it "titleText" or something (since a "tooltip" could mean a lot of different things).

I'm less excited about the data-attributes. I know it's not a lot of extra code but it still adds a bit more complexity and extra docs. I also don't feel like it has a strong use-case. Are you cool if we remove  that part?

I'm happy to make the changes if you're on board with them.

**Comment by catchmyfame** [comment]
I'm fine with removing the data-attribute part but I'm not sure how to keep the functionality without it. Suggestions?

**Comment by bryanbraun** [comment]
@catchmyfame, yeah I can't think of a better way to do anchor-specific title-text than data-attributes, so I guess I'm suggesting that we remove that feature altogether.

I feel like the global `titleText` attribute you proposed addresses [the need you mentioned here](https://github.com/bryanbraun/anchorjs/issues/100#issuecomment-427682472) and that anchor-specific text would only add marginal benefit.

**Comment by bryanbraun** [comment]
I'm going to go ahead and merge this but remove the data-attribute feature in a follow-up commit (for the reasons I mentioned in my last comment).

This way we still get the global title-text option.

Thanks for the feature request and the PR. It's much appreciated!

**Pull request merged**
