### PR TITLE
Normalize package.json

### PR DESCRIPTION
**Pull request by XhmikosR**
@bryanbraun feel free to add some keywords later, it should help.

### CODE REVIEW

**Comment by bryanbraun** [comment]
This looks pretty good. One question though... what does the "git+https" protocol mean? I'm not familiar with it starting with `git+` and I couldn't find much about it with a quick online search.

**Comment by XhmikosR** [comment]
It's the default in npm. If you do `npm init` you will get this.

**Comment by bryanbraun** [comment]
Oh, you're right. :)

Merging this now. 👍

**Comment by XhmikosR** [comment]
@bryanbraun the website field is used in the banner script and now it's `https://www.bryanbraun.com/anchorjs/` in anchor.min.js. I hadn't noticed this TBH, so if you don't like it just revert the `homepage` change :)

**Pull request merged**
