### PR TITLE
Adds trim option for generated anchors, and option overrides.

### PR DESCRIPTION
**Pull request by adjohnson916**

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey, I haven't been able to review this fully, but I just wanted to say that I'm looking over it a bit and I have some thoughts.

First, I think the whitespace trim is a great idea. Let's definitely add that but I'm thinking we should just drop the "option" and make it a standard part of the url generation. Big props for adding the tests. :raised_hands: 

The change to use `opts` instead of `that` looks a lot cleaner, but I feel like there was some reason I switched to using `that` in the first place, which I can't remember off the top of my head. If nothing breaks with this change then I'm all for it, but I just want to take a moment to figure out why I went that direction in the first place. Looks like this is the commit it was introduced: https://github.com/bryanbraun/anchorjs/commit/94ad5a63dbf02add213860ddf9e8878c441a65e2

**Comment by adjohnson916** [comment]
@bryanbraun All the tests do pass on this branch. It looks like you have Travis CI configured for this repo, so I'm not sure why it seems not to have run the tests for this pull request.

The switch to `opts` should not have changed any behavior - it's only scoped to the `_applyRemainingDefaultOptions` method so that I could re-use that method from the  `urlify` method to also default options there since it was exposed by this module and was used in some test cases.

I agree we could make the default `true` instead of `false`, but I wasn't sure if we'd consider it a breaking change and have to do a semver major release which you might be hesitant to do, so I kept it default to `false` for this pull request. I can change that, but I'd rather see this released sooner with a `false` default rather than wait for a `true` default.

**Comment by bryanbraun** [comment]
Ok. I've looked through using `opts`, and I'm good with that change.

Not sure why Travis didn't pick up on the PR. I'm guessing it was a fluke.

Happy to merge this now and do a major version increase later. :+1:

**Comment by bryanbraun** [comment]
FYI I'm making a couple minor changes once I merge this. We shouldn't need to pass options into urlify, since we can just change the options on the object itself.

**Comment by adjohnson916** [comment]
@bryanbraun Thanks!

I wasn't enthused about accepting options in the urlify method either, but it seemed the least painless way to add unit tests at the time.

Anyway, feel free to change the implementation, I'll just be glad to get the feature.

**Pull request merged**
