### PR TITLE
Support IDs specified with a data attribute

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request adds support for `data-id` attributes, which specify the anchor ID in cases when it's not on the header itself:

```html
<section id="some-section">
    <h2 data-id="some-section">Some section</h2>
</section>
```

For example, this can be used to [highlight the target section like this](http://canimod.com/for-players/faqs#error-log).

All tests pass, including a new test I added for `data-id`.

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey @Pathoschild, I was just looking at this today. It's a simple solution and I like it. 😄 

A small concern was that `data-id` was too generic... that somebody else using that data attribute for some other reason might get unexpected results. It doesn't seem too likely... they would have to be targeting the element containing `data-id` with `anchors.add()`, and they would have to not already have an ID on the element.

Still there's a chance. I might feel better if we rename it to something a bit less common like "data-target-id". Thoughts?

**Comment by Pathoschild** [comment]
That makes sense. Maybe `data-anchor-id`? I'd be okay with `data-target-id` too.

**Comment by bryanbraun** [comment]
I like `data-anchor-id`. If you want to update it, I'll test it out and merge.

**Comment by Pathoschild** [comment]
Updated! :)

**Pull request merged**
