### PR TITLE
Update devDependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
@bryanbraun have you switched to Node.js 16/npm >=7 yourself? If so, I will update the lock file (here) and CI (in a separate PR)

### CODE REVIEW

**Comment by bryanbraun** [comment]
I'm still mostly using node 14.16.0 locally. These dependencies can still be updated though right? Should I be using node 16 before merging these two PRs?

**Comment by XhmikosR** [comment]
You don't need to, I'm just asking so that I know which npm version to use :)

**Comment by bryanbraun** [comment]
Yeah, 16.x works for me!

**Review by bryanbraun — APPROVED** [review]
Looks great!

**Pull request merged**
